import { SettingType } from "@/types/setting";

export const DEFAULTSETTING : SettingType = {
    watchIdLive: "",
    ayat: "Mazmur 119:105",
    isiAyat: "Firman-Mu itu pelita bagi kakiku dan terang bagi jalanku.",
    title: "A Place To <b class='block'>Belong, Believe, </b> and <b>Become.</b>",
    welcomeText: "Welcome Home",
    kenangan: "Kenangan Berharga di Gereja",
    live: "Live Tour",
    liveDesc: "Ikuti ibadah gereja kami secara live dan rasakan kehangatan komunitas kami secara langsung.",
    renunganHarianHome: "Renungan Harian",
    renunganHarianHomeDesc: "Mulailah harimu dengan inspirasi dan penguatan dari Firman Tuhan. Luangkan waktu sejenak untuk berhenti, merenung, dan bersekutu dengan-Nya.",
    tentangGereja: "Tentang Gereja Kami",
    tentangGerejaButton: "Baca Lebih Lanjut",
    tentangGerejaDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    aboutBannerTitle: "Membimbing Perjalanan Iman dengan Benar",
    aboutDesc: "<p>Bertumbuh dalam iman, melayani dengan kasih, dan memberitakan Injil.</p>",
    aboutDesc2: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
    aboutMissionDesc: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>",
    aboutMissionTitle: "Our Mission",
    aboutStatementFaith: "Statement of Faith",
    aboutStatementFaithDesc: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>",
    aboutTitle: "GKIm Amanat Kristus",
    aboutTitle2: "Who we really are  & why choose us",
    aboutVisionDesc: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>",
    aboutVisionTitle: "Our Vission",
    address: "Jalan Raya Kopo No. 246, Bandung",
    addressTitle: "Kunjungi gereja kami dan beribadah bersama",
    faqTitle: "Pertanyaan yang Sering Diajukan (FAQ)",
    hubTitle: "Hubungi kami dan bertumbuh dalam iman bersama",
    leaderDesc: "<p>Inilah para pemimpin gereja kami yang melayani dengan iman dan dedikasi untuk membimbing serta mendukung jemaat. Kenali mereka dan visi pelayanannya.</p>",
    leaderTitle: "Get to Know Our Church Leaders",
    waNumber: "+6282 122 790 090",
    waTitle: "Hubungi kami untuk dukungan rohani",
    mapsButtonLabel: "See The Map",
    renunganDesc1: "<p>Semua tentang Iman, Doa, dan Kedekatan dengan Tuhan</p>",
    renunganDesc2: "<p>Artikel Terkini Tentang Inspirasi Iman Terkini</p>",
    renunganTitle1: "Firman. Kehidupan. Kebenaran.",
    renunganTitle2: "Renungan Terkini"
}