import { Document } from "mongoose"

export interface ISettingDocument extends Document {
    watchIdLive: string,
    welcomeText: string,
    title: string,
    ayat: string,
    isiAyat: string,
    tentangGereja: string,
    tentangGerejaDesc : string,
    tentangGerejaButton: string,
    renunganHarianHome : string,
    renunganHarianHomeDesc :string,
    live: string,
    liveDesc: string,
    kenangan: string,
    aboutTitle: string,
    aboutDesc: string,
    aboutTitle2: string,
    aboutDesc2: string,
    aboutBannerTitle : string,
    aboutMissionTitle: string,
    aboutMissionDesc: string,
    aboutVisionTitle: string,
    aboutVisionDesc: string,
    aboutStatementFaith:string,
    aboutStatementFaithDesc: string,
    leaderTitle: string,
    leaderDesc: string,
    faqTitle: string,
    hubTitle: string,
    waTitle: string,
    waNumber: string,
    addressTitle: string,
    address: string,
    mapsButtonLabel: string
}

export interface ISettingModel extends Document {
    
}

export type SettingType = {
    watchIdLive: string,
    welcomeText: string,
    title: string,
    ayat: string,
    isiAyat: string,
    tentangGereja: string,
    tentangGerejaDesc : string,
    tentangGerejaButton: string,
    renunganHarianHome : string,
    renunganHarianHomeDesc :string,
    live: string,
    liveDesc: string,
    kenangan: string,
    aboutTitle: string,
    aboutDesc: string,
    aboutTitle2: string,
    aboutDesc2: string,
    aboutBannerTitle : string,
    aboutMissionTitle: string,
    aboutMissionDesc: string,
    aboutVisionTitle: string,
    aboutVisionDesc: string,
    aboutStatementFaith:string,
    aboutStatementFaithDesc: string,
    leaderTitle: string,
    leaderDesc: string,
    faqTitle: string,
    hubTitle: string,
    waTitle: string,
    waNumber: string,
    addressTitle: string,
    address: string,
    mapsButtonLabel: string
}