import { RSVP } from '@/type/rsvp';
import { JWT } from 'google-auth-library';
import { GoogleSpreadsheet } from 'google-spreadsheet';

export async function GET() {
    return Response.json({
        message: "Hi"
    })
}

const SPREADSHEET_ID = process.env.SPREADSHEET_ID ?? "";
const SHEET_ID = process.env.SHEET_ID;
const GOOGLE_CLIENT_EMAIL = process.env.GOOGLE_CLIENT_EMAIL;
const GOOGLE_SERVICE_PRIVATE_KEY = process.env.GOOGLE_SERVICE_PRIVATE_KEY;

const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: GOOGLE_CLIENT_EMAIL,
    key: GOOGLE_SERVICE_PRIVATE_KEY!.replace(/\\n/g, '\n'),
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

// GoogleSpreadsheet Initialize
const doc = new GoogleSpreadsheet(SPREADSHEET_ID, serviceAccountAuth);

const appendSpreadsheet = async (row : RSVP) => {
    try {
      // loads document properties and worksheets
      await doc.loadInfo();
        
      const sheet = doc.sheetsById[Number(SHEET_ID ?? 0)];
      console.log(sheet);
      await sheet.addRow(row);
    } catch (e) {
      console.error('Error: ', e);
    }
  };

export async function POST(request: Request) {
    const { nama, jumlahTamu } = await request.json();

    await appendSpreadsheet({
        nama,
        jumlahTamu
    })

    return Response.json({
        nama
    })
}
